#!/bin/bash
if [ ! -f ./github-release ]; then
  wget -qO- https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2 |tar xvj --strip=3
fi

TAG=v`./node_modules/.bin/json -f package.json -c 'console.log(this.version)'`
GH_TOKEN=`./node_modules/.bin/json -f ~/.github.json -c 'console.log(this.OAuth)'`
CRED="-s $GH_TOKEN --user akaJes --repo jesed --tag $TAG"

./github-release release $CRED --name "jesed"

for file in `ls build`; do
  echo "publicate file  $file"
  ./github-release upload $CRED --name $file --file build/$file
done
